// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCOA2rXp9UJuLJRsIyqaX0RWBlVZB0CEqU',
//     appId: '1:628302252156:web:e26f78fca5c86a6d83a1f9',
//     messagingSenderId: '628302252156',
//     projectId: 'skill-rat',
//     authDomain: 'skill-rat.firebaseapp.com',
//     storageBucket: 'skill-rat.firebasestorage.app',
//     measurementId: 'G-PLXR69ZRLK',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBQIGA6Tn09tne145w7mIfm80B52taB6RE',
//     appId: '1:628302252156:android:d765e9494de5a02883a1f9',
//     messagingSenderId: '628302252156',
//     projectId: 'skill-rat',
//     storageBucket: 'skill-rat.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCeIf2XL3gJs0r1uE0HBEJeDWA63TKM_Yw',
//     appId: '1:628302252156:ios:a2fc9b86953299eb83a1f9',
//     messagingSenderId: '628302252156',
//     projectId: 'skill-rat',
//     storageBucket: 'skill-rat.firebasestorage.app',
//     iosBundleId: 'com.skillrat',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCeIf2XL3gJs0r1uE0HBEJeDWA63TKM_Yw',
//     appId: '1:628302252156:ios:6b70dfb0149069f283a1f9',
//     messagingSenderId: '628302252156',
//     projectId: 'skill-rat',
//     storageBucket: 'skill-rat.firebasestorage.app',
//     iosBundleId: 'com.example.skillRat',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCOA2rXp9UJuLJRsIyqaX0RWBlVZB0CEqU',
//     appId: '1:628302252156:web:9c241ddcd6fe999e83a1f9',
//     messagingSenderId: '628302252156',
//     projectId: 'skill-rat',
//     authDomain: 'skill-rat.firebaseapp.com',
//     storageBucket: 'skill-rat.firebasestorage.app',
//     measurementId: 'G-42QE8S6K20',
//   );
// }
